export const START_AUTHENTICATION = 'START_AUTHENTICATION'
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL'
export const AUTHORIZATION_SUCCESSFUL = 'AUTHORIZATION_SUCCESSFUL'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED'
export const CLEAR_AUTH_MESSAGES = 'CLEAR_AUTH_MESSAGES'
export const SET_DISABLED = 'SET_DISABLED'

export const SET_CONFIRM_SUCCESS_MESSAGE = 'SET_CONFIRM_SUCCESS_MESSAGE'
export const SET_CONFIRM_FAIL_MESSAGE = 'SET_CONFIRM_FAIL_MESSAGE'
export const CLEAR_CONFIRM_ALL_MESSAGES = 'CLEAR_CONFIRM_ALL_MESSAGES'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR'
