// Auth reducer
export const START_AUTHENTICATION = 'START_AUTHENTICATION'
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL'
export const AUTHORIZATION_SUCCESSFUL = 'AUTHORIZATION_SUCCESSFUL'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED'
export const CLEAR_AUTH_MESSAGES = 'CLEAR_AUTH_MESSAGES'
export const SET_DISABLED = 'SET_DISABLED'

// Confirm reducer
export const SET_CONFIRM_SUCCESS_MESSAGE = 'SET_CONFIRM_SUCCESS_MESSAGE'
export const SET_CONFIRM_FAIL_MESSAGE = 'SET_CONFIRM_FAIL_MESSAGE'
export const CLEAR_CONFIRM_ALL_MESSAGES = 'CLEAR_CONFIRM_ALL_MESSAGES'

// Sidebar reducer
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR'

// User reducer
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'
export const CLEAR_REDIRECT_TO_MAIN = 'CLEAR_REDIRECT_TO_MAIN'

// Employee reducer
export const FETCH_ALL_EMPLOYEES_REQUEST = 'FETCH_ALL_EMPLOYEES_REQUEST'
export const FETCH_ALL_EMPLOYEES_SUCCESS = 'FETCH_ALL_EMPLOYEES_SUCCESS'
export const FETCH_ALL_EMPLOYEES_FAILURE = 'FETCH_ALL_EMPLOYEES_FAILURE'
// Get 1 employee
export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST'
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE'
// Create
export const FETCH_CREATE_EMPLOYEE_REQUEST = 'FETCH_CREATE_EMPLOYEE_REQUEST'
export const FETCH_CREATE_EMPLOYEE_SUCCESS = 'FETCH_CREATE_EMPLOYEE_SUCCESS'
export const FETCH_CREATE_EMPLOYEE_FAILURE = 'FETCH_CREATE_EMPLOYEE_FAILURE'
// Edit
export const FETCH_EDIT_EMPLOYEE_REQUEST = 'FETCH_EDIT_EMPLOYEE_REQUEST'
export const FETCH_EDIT_EMPLOYEE_SUCCESS = 'FETCH_EDIT_EMPLOYEE_SUCCESS'
export const FETCH_EDIT_EMPLOYEE_FAILURE = 'FETCH_EDIT_EMPLOYEE_FAILURE'
// Dismiss
export const FETCH_DISMISS_EMPLOYEE_SUCCESS = 'FETCH_DISMISS_EMPLOYEE_SUCCESS'
export const FETCH_DISMISS_EMPLOYEE_FAILURE = 'FETCH_DISMISS_EMPLOYEE_FAILURE'
// Modals
export const SET_MODAL_CREATE_ACTIVE = 'SET_MODAL_CREATE_ACTIVE'
export const SET_MODAL_EDIT_ACTIVE = 'SET_MODAL_EDIT_ACTIVE'
export const HIDE_MODAL_EMPLOYEE_EDIT = 'HIDE_MODAL_EMPLOYEE_EDIT'

// Department reducer
export const FETCH_CREATE_DEPARTMENT_REQUEST = 'FETCH_CREATE_DEPARTMENT_REQUEST'
export const FETCH_CREATE_DEPARTMENT_SUCCESS = 'FETCH_CREATE_DEPARTMENT_SUCCESS'
export const FETCH_CREATE_DEPARTMENT_FAILURE = 'FETCH_CREATE_DEPARTMENT_FAILURE'
export const FETCH_ALL_DEPARTMENT_SUCCESS = 'FETCH_ALL_DEPARTMENT_SUCCESS'
export const FETCH_ALL_DEPARTMENT_FAILURE = 'FETCH_ALL_DEPARTMENT_FAILURE'
export const SET_DEPARTMENT_MODAL_ACTIVE = 'SET_DEPARTMENT_MODAL_ACTIVE'

// Role reducer
export const FETCH_ALL_ROLE_SUCCESS = 'FETCH_ALL_ROLE_SUCCESS'
export const FETCH_ALL_ROLE_FAILURE = 'FETCH_ALL_ROLE_FAILURE'
